import { sessionInfo } from "./session";

export const LV100Battles = [
    {
        BattleName:"奇襲",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    },
    {
        BattleName:"魔神之塔",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    },
    {
        BattleName:"馬夏的試煉",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    },
    {
        BattleName:"狂氣之墓",
        sessions:[
            {
                session:1,
                money:0
            },
            {
                session:2,
                money:0
            },
        ]
    },
    {
        BattleName:"光輝的魯",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    },
    {
        BattleName:"艾維卡的夢魘",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    },
    {
        BattleName:"地底實驗室",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    },
    {
        BattleName:"為了不要遺忘",
        /*sessions:[
            {
                session:1,
                money:20
            },
            {
                session:2,
                money:0
            }
        ]*/
    }
];